### ISSUE TITLE
Create chat form signup

### ISSUE THREAD

**Issue by ktsuench** [ruhacks/ruhacks-tasks#13]
Looking back at issue #5, I suggested looking into using this [library](https://github.com/space10-community/conversational-form) and trying an implementation. We need to have this done by mid December as applications will be open for late December.

**Comment by zsalehi** [comment]
[here](https://github.com/space10-community/conversational-form) is a great way to get the conversational form implementation reall quick..
i can have a demo of this setup if you guys want by the end of the week

**Comment by ktsuench** [comment]
@zsalehi that's the one have suggest as well in the issue outline

It would be good if you can build the actual form itself. I'll pass on the required details for what's needed for profile information.

- [ ] get list of required hacker info
- [ ] implement the signup as a conversation form
- [ ] submit data from the form to firebase

**Comment by ktsuench** [comment]
Btw create this as another repository, call it `hacker-application`. This project will be responsible for sign up, login, and updating profile.

**Comment by jas2996** [comment]
@zsalehi Would you be able to have a working demo at the end of this week?

**Comment by zsalehi** [comment]
the form is ready. now i just gotta make it conversational and style it so that the demo will be ready. debating on whether to use node package or just plain JS .. may go the plain JS route and also gotta get all the conditionals in for the form so thats sorta what the update will be for this weekend... will have a demo ready for late Sunday or Monday. Been a crazy week with work and my startups so i had to prioritize.... very sorry for that! Should be back on track for next week.

**Comment by ktsuench** [comment]
Awesome work. Keep us updated and make sure to commit changes to the repository for to checkout. 👍  Keep up the good work!

**Comment by ktsuench** [comment]
We'll keep track of the work in the repo hacker-application. Closing this issue.

**Comment by ktsuench** [comment]
refer to issue ruhacks/hacker-application#2
